# Generated by Django 6.0.3 on 2026-06-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichierMP3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='mp3/')),
                ('duree_secondes', models.IntegerField(blank=True, null=True)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
